unreadable_zip: "Unreadable zip archive."
s3_error: "Unable to download file from s3."
no_task: "There is no task file inside the archive."
extension: "Incorrect extension of the task file inside the archive."
unreadable_file: "Unable to read file."
no_data_field: "There is no date field in the task file."
no_split: "There is no test field in the task file."
no_outputs_field_for_doc: "Unable to get the outputs field from the task file for document with sequence number (not id) example_number."
no_meta_field_for_doc: "Unable to get the meta field from the task file for document with sequence number (not id) example_number."
no_id_field_for_doc: "Unable to get the id field from the task file for document with sequence number (not id) example_number."
no_id: "There is no document with id in the task file."
doc_output_type_error: "The type of the outputs field does not match the expected type."
doc_parse_output_error: "Error receiving outputs for the document (the field exists, but it cannot be parsed)."
task_system_error: "An unexpected system error occurred while validating and evaluating the task."